sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "3.5"

env:
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TRANSIFEX="1" TRANSIFEX_USER='transbot@odoo-community.org'
  - DOCS="1"
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" DOCS="0"
    # travis for docs build
  - secure: "lazdZGpkqFTQiu44grYAqKcaGh0cVTBlrHcBxxs43K/OH4Uc2AjMBty83zKc0ZgzizrNOsfK3Z3UHLmTNI92Vi3PtgGzA9dUmiReGO6QcE9P31Geg4pN/1Fwosv6aSpG3hejJJ8ZYpMbEPJkZyjTVpdM2r1VEcqEvFQ2xR5bEUg="
    # transifex
  - secure: "HLsfDkckZKfcyIFdLLYI2Q/SKBsI48QoYKJm2WSttlSIp4Bli6rYc/2WLwcKyQmkS0TITYRhKAjzBYYHZCThj77lwQgXFm5Di+MFpDbH5R5llCdQJD+A5gSs/GxzIEXX6YxVajcLe6MrI15pdv3p9Bl8K14owLXZaypvkV1XrBA="

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install sphinx sphinx_bootstrap_theme sphinx-intl
    # install from sources because it includes a fix for Odoo 12.0 not released yet
  - pip install git+https://github.com/OCA/odoo-sphinx-autodoc.git
  - if [ "$DOCS" = "1" ] ; then pip install -e ${HOME}/odoo-12.0; fi

services:
  - postgresql

script:
  - if [ "$DOCS" != "1" ] ; then travis_run_tests; fi
  - if [ "$DOCS" == "1" ] ; then ./.travis_build_doc; fi

after_success:
  - if [ "$DOCS" != "1" ] ; then travis_after_test_success; fi
  - if [ "$DOCS" == "1" ] ; then ./.travis_push_doc; fi
